[package]
name = "undefined_behavior"
version = "0.0.2"
authors = ["Vincent Combey <vcombey@student.42.fr>", "Mickael Billod <bmickael@student.42.fr>", "Sebastien Clolus <sclolus@student.42.fr>"]
edition = "2018"

[profile.release]
opt-level = 3
debug = false
panic = "abort"

[profile.dev]
panic = "abort"
debug = true

[lib]
crate-type = ["staticlib"]

[dependencies]
bit_field = "0.9.0"
bitflags = "1.0.4"
log = "0.4.6"
lock_api = "0.1.5"
hashmap_core = "0.1.10"
io = { path = "dependencies/io" }
keyboard = { path = "dependencies/keyboard" }
mbr = { path = "dependencies/mbr" }
raw_data = { path = "dependencies/raw_data" }
const_assert = { path = "dependencies/const_assert" }
ext2 = { path = "dependencies/ext2" }

[dependencies.lazy_static]
version = "1.3.0"
features = ["spin_no_std"]

[dev-dependencies]
[features]
exit-on-panic = []
serial-eprintln = []
#test-succeed= []
#test-failed= []
test-sodo-allocator= []
test-vmalloc= []
test-kmalloc= []
native-test-hard-drive-read-pio = []
native-test-hard-drive-write-pio = []
native-test-hard-drive-read-bios = []
native-test-hard-drive-write-bios = []
test = []