[package]
name = "undefined_behavior"
version = "0.0.2"
authors = ["Vincent Combey <vcombey@student.42.fr>", "Mickael Billod <bmickael@student.42.fr>", "Sebastien Clolus <sclolus@student.42.fr>"]
edition = "2018"

[profile.release]
opt-level = 3
panic = "abort"

[profile.dev]
panic = "abort"

[lib]
crate-type = ["staticlib"]

[dependencies]
bit_field = "0.9.0"

[features]
qemu-graphical= []
#test-succeed= []
#test-failed= []
test = []
