[package]
name = "undefined_behavior"
version = "0.0.2"
authors = ["Vincent Combey <vcombey@student.42.fr>", "Mickael Billod <bmickael@student.42.fr>"]
edition = "2018"

[profile.release]
opt-level = 1

[lib]
crate-type = ["staticlib"]

[dependencies]