[package]
name = "vfs_tests"
version = "0.1.0"
authors = ["miniske"]
edition = "2018"

[dependencies]
walkdir = "2"
libc_binding = { path = "../../dependencies/libc_binding" }
const_assert = { path = "../../dependencies/const_assert" }
bitflags = "*"
itertools = "*"