[package]
name = "mordak"
version = "0.1.0"
authors = ["mordak <bmickael@student.42.fr>"]
edition = "2018"

[profile.release]
opt-level = 3
debug = false
panic = "abort"

[lib]
crate-type = ["staticlib"]

[dependencies]
bit_field = "0.9.0"