[package]
name = "nucleus"
version = "0.1.0"
authors = ["Steve Klabnik <steve@steveklabnik.com>", "Amit Aryeh Levy <amit@amitlevy.com>"]
edition = "2018"

[lib]
crate-type = ["staticlib"]

[dependencies]